name: BedWar
main: org.sobadfish.bedwar.BedWarMain
version: 1.8.4
api:
  - 1.0.11
  - 3.0.0
author: sobadfish&GouDan888
load: POSTWORLD
description: "起床战争小游戏插件"

softdepend:
  - RsNPC
  - ScoreboardPlugin
  - AutoUpData
  - Tips

loadbefore:
  - ScoreboardPlugin
