name: BedWar
main: org.sobadfish.bedwar.BedWarMain
version: 2.1.8
api:
  - 1.0.11
  - 3.0.0
author: sobadfish
load: POSTWORLD
description: "起床战争小游戏插件"

softdepend:
  - RsNPC
  - ScoreboardPlugin
  - AutoUpData
  - Tips
  - Ghosty

loadbefore:
  - ScoreboardPlugin
